In [1]:
import nltk
from nltk.corpus import stopwords
# nltk.download()
# nltk.download('wordnet')
from nltk.tokenize import sent_tokenize, word_tokenize
# nltk.download()
from sklearn.model_selection import GridSearchCV
import pandas as pd
import re
from sklearn.model_selection import train_test_split
from nltk.stem import WordNetLemmatizer
from sklearn.ensemble import RandomForestClassifier
from sklearn import linear_model
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score
import pickle
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix,plot_confusion_matrix

In [6]:
df_train = pd.read_csv("train.txt",delimiter=';',names=['text','label'])
df_val = pd.read_csv("val.txt",delimiter=';',names=['text','label'])
df = pd.concat([df_train,df_val])

df.reset_index(drop=True,inplace=True)
# df['label'].unique()
# df

In [3]:
# data=pd.read_csv("custom_dataset_for_train.csv")
# data

In [8]:
# df_train

In [10]:
def enco(df):
    df.replace(to_replace="surprise",value=1,inplace=True)
    df.replace(to_replace="joy",value=2,inplace=True)
    df.replace(to_replace="love",value=2,inplace=True)
    df.replace(to_replace="sadness",value=3,inplace=True)
    df.replace(to_replace="anger",value=3,inplace=True)
    df.replace(to_replace="fear",value=1,inplace=True)
    
enco(df.label)
enco(df_train)
# enco
# df.to_csv("df_enco.csv")
# df_train.to_csv("df_enco_train.csv")
# 1-Neutral
# 2-Positive
# 3-Negative

<function __main__.enco(df)>

In [11]:
pd1=pd.read_csv("df_enco.csv")
pd1

Unnamed: 0                                               text  label
0               0                            i didnt feel humiliated      3
1               1  i can go from feeling so hopeless to so damned...      3
2               2   im grabbing a minute to post i feel greedy wrong      3
3               3  i am ever feeling nostalgic about the fireplac...      2
4               4                               i am feeling grouchy      3
...           ...                                                ...    ...
17995       17995  im having ssa examination tomorrow in the morn...      3
17996       17996  i constantly worry about their fight against n...      2
17997       17997  i feel its important to share this info for th...      2
17998       17998  i truly feel that if you are passionate enough...      2
17999       17999  i feel like i just wanna buy any cute make up ...      2

[18000 rows x 3 columns]

In [17]:
fina=[]
def conver(data):
    for val in range(len(data)):
        lm = WordNetLemmatizer()
        stopword=set(stopwords.words("english"))
        wor=re.sub("[^A-Za-z]",' ',str(data[val]))
        wor=wor.lower() 
        wor=wor.split()
        wor = [lm.lemmatize(word) for word in wor if word not in set(stopwords.words('english'))]    
        tex=[]
        for ijx in wor:
            if ijx not in stopword:
                tex.append(lm.lemmatize(ijx))
        fina.append(" ".join(tex))
    print(fina)
    print(len(fina))    
    
train_fina=[]
def train_conver(data):
    for val in range(len(data)):
        lm = WordNetLemmatizer()
        stopword=set(stopwords.words("english"))
        wor=re.sub("[^A-Za-z]",' ',str(data[val]))
        wor=wor.lower() 
        wor=wor.split()
        wor = [lm.lemmatize(word) for word in wor if word not in set(stopwords.words('english'))]    
        tex=[]
        for ijx in wor:
            if ijx not in stopword:
                tex.append(lm.lemmatize(ijx))
        train_fina.append(" ".join(tex))
    print(train_fina)
    print(len(train_fina))
    

    

In [18]:
# conver(df.text)
# train_conver(df_train.text)

# fina_data=pd.DataFrame(fina,columns=["process"])
# fina_data.to_csv("processed.csv")

# train_da=pd.DataFrame(train_fina,columns=["process"])
# train_da.to_csv("train_process.csv")

In [19]:
process_data=pd.read_csv("processed.csv")
process_data["process"]
train_process=pd.read_csv("train_process.csv")
# train_process=pd.read_csv("custom_dattt.csv")
train_process["process"]
process_data["process"]

0                                    didnt feel humiliated
1        go feeling hopeless damned hopeful around some...
2                im grabbing minute post feel greedy wrong
3        ever feeling nostalgic fireplace know still pr...
4                                          feeling grouchy
                               ...                        
17995    im ssa examination tomorrow morning im quite w...
17996    constantly worry fight nature push limit inner...
17997           feel important share info experience thing
17998    truly feel passionate enough something stay tr...
17999    feel like wanna buy cute make see online even one
Name: process, Length: 18000, dtype: object

In [20]:
vector=CountVectorizer()
x=vector.fit_transform(process_data["process"])
test=vector.transform(train_process["process"])
x.toarray()
# test.toarray()



array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
param={'n_estimators':[100,200,300],
      'criterion':['gini','entropy'],
#       'max_depth':[10,20,30,40,50,60,70,80,90,100],
#        'max_features':['auto','log2','sqrt'],
#        'min_sample_leaf':[3,5,7,9,11],
#        'min_samples_split': [2,5,10]
      }
# ,13,15,17,19,21,23,25 min sample

In [22]:
model=RandomForestClassifier()
grid=GridSearchCV(model,param,verbose=5,cv=10)


In [23]:
# # grid.fit(x,df.label)  
# grid.fit(x,pd.label) 

In [25]:
# pickle.dump(grid, open("grid_model_with_2_hp_22.pkl", "wb"))
# 
# gridd = pickle.load(open("grid_model_with_2_hp_22.pkl", "rb"))

# pickle.dump(grid, open("grid_model_with_2_hp_22_v2.pkl", "wb"))
# 
gridd = pickle.load(open("grid_model_with_2_hp_22_v2.sav", "rb"))

# pickle.dump(grid, open("grid_model_with_2_hp_22_v2.sav", "wb"))

# pickle.dump(vector, open("vector.sav", "wb"))



In [26]:
gridd

GridSearchCV(cv=10, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'n_estimators': [100, 200, 300]},
             verbose=5)

In [43]:
print(gridd.cv_results_)
print(gridd.best_estimator_)
print(gridd.best_index_)
print(gridd.best_params_)
print(gridd.best_score_)

{'mean_fit_time': array([ 45.64792011,  88.43347309, 138.28526597,  47.3294764 ,
        96.37987373, 127.95948763]), 'std_fit_time': array([ 1.2120378 ,  4.56925528,  5.13171048,  2.72902376, 10.20586326,
        6.63700181]), 'mean_score_time': array([0.18518181, 0.36460633, 0.56332965, 0.18577433, 0.38442297,
       0.52349634]), 'std_score_time': array([0.01733312, 0.02334599, 0.03052058, 0.01316714, 0.04087396,
       0.02008944]), 'param_criterion': masked_array(data=['gini', 'gini', 'gini', 'entropy', 'entropy',
                   'entropy'],
             mask=[False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_n_estimators': masked_array(data=[100, 200, 300, 100, 200, 300],
             mask=[False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'criterion': 'gini', 'n_estimators': 100}, {'criterion': 'gini', 'n_estimators': 200}, {'criterion': 'gini', 'n_estimators': 300}, {'cri

In [28]:
predic_grid_random=gridd.predict(test)
acc_grid_random=accuracy_score(df_train.label,predic_grid_random)
acc_grid_random


0.9995

In [44]:
#Confusion Matrix

confusion_matrix(y_true=df_train.label,y_pred=predic_grid_random)



result=confusion_matrix(y_true=df_train.label,y_pred=predic_grid_random)
print(result)
True_Positive =result[0][0]
False_Negative=result[0][1]+result[0][2]
False_Positive=result[1][0]+result[2][0]
True_Negative=result[1][1]+result[2][2]
print(f"True Positive :{True_Positive}")
print(f"False Negative :{False_Negative}")
print(f"False Positive :{False_Positive}")
print(f"True Negative :{True_Negative}")
matrix=[[True_Positive,False_Negative],[False_Positive,True_Negative]]
print(np.matrix(matrix))

[[2507    0    2]
 [   1 6665    0]
 [   5    0 6820]]
True Positive :2507
False Negative :2
False Positive :6
True Negative :13485
[[ 2507     2]
 [    6 13485]]


In [30]:
# nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn

inp=input("Enter")
# gridd.predict(test)
train_fina=[]
# for val in range(len(df_train.text)):
lm = WordNetLemmatizer()
stopword=set(stopwords.words("english"))
wor=re.sub("[^A-Za-z]",' ',str(inp))
wor=wor.lower()    
wor=wor.split()
wor = [lm.lemmatize(word) for word in wor if word not in set(stopwords.words('english'))]
tex=[]
for ijx in wor:
    if ijx not in stopword:
        tex.append(lm.lemmatize(ijx))
train_fina.append(" ".join(tex))
print(train_fina)
print(len(train_fina))        
test=vector.transform(train_fina)
predic=gridd.predict(test)
# predic[0]

# if(predic[0] == 1):
#     print("Surprice")
    
# if(predic[0] == 2):
#     print("Joy")
# if(predic[0] == 3):
#     print("Love")
# if(predic[0] == 4):
#     print("Sadness")
# if(predic[0] == 5):
#     print("Anger")
# if(predic[0] == 6):
#     print("Fear")


# nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn

EnterHi All. I have purchased OP Nord 2 for upgrade from my two years old Realme X. But my experience with Nord 2 is very bad. first its display is very bad quality compare to smartphone at 30k range. Even my Realme x display looking good against Nord 2. Its major highlight camera also very poor quality nowhere near to flagship sensor as OP advertising. Daylight pics are pathetic. After system update App Clone function is not working not able to use my 2nd whats app account. Call Recording function is not working which is my main requirement that is working flawless in my realme x. I think OnePlus make fool of us. Everyone who is purchasing will regret afterwards. So beware of OP Nord 2.
['hi purchased op nord upgrade two year old realme x experience nord bad first display bad quality compare smartphone k range even realme x display looking good nord major highlight camera also poor quality nowhere near flagship sensor op advertising daylight pic pathetic system update app clone functi

In [40]:


def check(inpp):
    train_fina=[]
    # for val in range(len(df_train.text)):
    lm = WordNetLemmatizer()
    stopword=set(stopwords.words("english"))
    wor=re.sub("[^A-Za-z]",' ',str(inpp))
    wor=wor.lower()    
    wor=wor.split()
    wor = [lm.lemmatize(word) for word in wor if word not in set(stopwords.words('english'))]
    tex=[]
    for ijx in wor:
        if ijx not in stopword:
            tex.append(lm.lemmatize(ijx))
    train_fina.append(" ".join(tex))
    print(train_fina)
    print(len(train_fina))        
    test=vector.transform(train_fina)
    predic=gridd.predict(test)
    predic[0]

    if(predic[0] == 1):
        print("Neutral")

    if(predic[0] == 2):
        print("Positive")
    if(predic[0] == 3):
        print("Negative")
    # if(predic[0] == 4):
    #     print("Sadness")
    # if(predic[0] == 5):
    #     print("Anger")
    # if(predic[0] == 6):
    #     print("Fear")

    # elif(predic[0] == 0):
    #     print("sadness, anger, fear")

inp=input()
check(inp)

I don't why the youtube community discourage this phone but it's now a month I have been using this phone and is the best ever device in 2021. Please don't hesitate, don't keep any second thoughts just go for it. One plus is one plus and not just ant brand out there and thanks to Amazon for providing me huge discount offer I got this product some what near 20ishhh. And I am delighted about it..
['youtube community discourage phone month using phone best ever device please hesitate keep second thought go one plus one plus ant brand thanks amazon providing huge discount offer got product near ishhh delighted']
1
Positive
